apiVersion: apps/v1
kind: Deployment
metadata:
  name: cxr-inference-gpu
  namespace: inference
  labels:
    app: cxr-inference-gpu

spec:
  replicas: 1
  selector:
    matchLabels:
      app: cxr-inference-gpu

  template:
    metadata:
      labels:
        app: cxr-inference-gpu

    spec:
      containers:
      - name: inference-gpu
        image: localhost/cxr-gpu:latest
        imagePullPolicy: IfNotPresent

        ports:
          - containerPort: 8000

        env:
          - name: MODEL_TYPE
            value: "gpu"

        volumeMounts:
          - name: preprocessing-config
            mountPath: /app/config/preprocessing_config.json
            subPath: preprocessing_config.json

          - name: model-volume
            mountPath: /app/model/victorio_cxr_best.pt

        resources:
          requests:
            cpu: "1000m"
            memory: "3Gi"
          limits:
            cpu: "2000m"
            memory: "6Gi"
            nvidia.com/gpu: 1

        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10

      volumes:
        - name: preprocessing-config
          configMap:
            name: preprocessing-config

        - name: model-volume
          hostPath:
            path: /var/tmp/victorio_cxr_best.pt
            type: File
