apiVersion: apps/v1
kind: Deployment
metadata:
  name: cxr-inference-cpu
  namespace: inference
  labels:
    app: cxr-inference-cpu

spec:
  replicas: 1
  selector:
    matchLabels:
      app: cxr-inference-cpu

  template:
    metadata:
      labels:
        app: cxr-inference-cpu

    spec:
      containers:
      - name: inference-cpu
        image: cxr-api:cpu
        imagePullPolicy: IfNotPresent

        ports:
          - containerPort: 8000

        env:
          - name: MODEL_TYPE
            value: "cpu"

        volumeMounts:
          - name: preprocessing-config
            mountPath: /app/config/preprocessing_config.json
            subPath: preprocessing_config.json

          - name: model-volume
            mountPath: /app/model/victorio_cxr_best.pt

        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10

      volumes:
        - name: preprocessing-config
          configMap:
            name: preprocessing-config

        - name: model-volume
          hostPath:
            path: /var/tmp/victorio_cxr_best.pt
            type: File
