apiVersion: apps/v1
kind: Deployment
metadata:
  name: cxr-inference-gpu
  namespace: inference
  labels:
    app: cxr-inference-gpu

spec:
  replicas: 1
  selector:
    matchLabels:
      app: cxr-inference-gpu

  template:
    metadata:
      labels:
        app: cxr-inference-gpu

    spec:
      nodeSelector:
        type: "gpu"

      containers:
      - name: inference-gpu
        image: localhost:5000/cxr-gpu:latest
        imagePullPolicy: IfNotPresent

        ports:
          - containerPort: 8000

        resources:
          limits:
            cpu: "4000m"
            memory: "16Gi"
          requests:
            nvidia.com/gpu: 1
            cpu: "2000m"
            memory: "8Gi"

        env:
          - name: MODEL_TYPE
            value: "gpu"

        volumeMounts:
          - name: preprocessing-config
            mountPath: /app/config/preprocessing_config.json
            subPath: preprocessing_config.json

      volumes:
        - name: preprocessing-config
          configMap:
            name: preprocessing-config