apiVersion: v1
kind: Service
metadata:
  name: cxr-inference-cpu
  namespace: inference
spec:
  selector:
    app: cxr-inference-cpu
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP